version: '3'
services: 
    mailer:
        image: schickling/mailcatcher
        container_name: mailer
        ports:
            - "1025"
            - "1080"
    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - "5672"
            - "15672"

